/**
 * PR Generator — Creates a pull request description from the agent's work.
 *
 * Produces a formatted markdown PR body with:
 * - Summary of changes
 * - Root cause analysis
 * - Files modified with diffs
 * - Test results
 * - Link back to the issue
 */

/**
 * Generate a complete PR description.
 *
 * @param {object} params
 * @param {object} params.issue — Parsed issue
 * @param {object} params.plan — Execution plan
 * @param {CodeChange[]} params.changes — Applied code changes
 * @param {object} params.testResult — Final test results
 * @param {object[]} params.iterations — Self-correction iterations
 * @returns {object} { title, body, labels, branch }
 */
export function generatePR({ issue, plan, changes, testResult, iterations }) {
  const title = generateTitle(issue, plan);
  const body = generateBody({ issue, plan, changes, testResult, iterations });
  const branch = generateBranchName(issue);
  const labels = generateLabels(issue, plan);

  return { title, body, branch, labels };
}

function generateTitle(issue, plan) {
  // Convention: "fix: <concise description> (#issue)"
  const prefix = plan.rootCause.includes('null') ? 'fix' : 'fix';
  const description = issue.title.length > 60
    ? issue.title.slice(0, 57) + '...'
    : issue.title;

  return `${prefix}: ${description}`;
}

function generateBody({ issue, plan, changes, testResult, iterations }) {
  const sections = [];

  // Header
  sections.push(`## Summary\n`);
  sections.push(plan.summary);
  sections.push('');

  // Link to issue
  if (issue.url || issue.number) {
    sections.push(`Fixes ${issue.url || `#${issue.number}`}`);
    sections.push('');
  }

  // Root cause
  sections.push(`## Root Cause\n`);
  sections.push(plan.rootCause);
  sections.push('');

  // Changes
  sections.push(`## Changes\n`);
  if (changes.length === 0) {
    sections.push('No code changes were generated.');
  } else {
    for (const change of changes) {
      sections.push(`### \`${change.file}\` (${change.action})`);
      sections.push('');
      sections.push(change.description);
      sections.push('');
      sections.push('```diff');
      sections.push(change.diff);
      sections.push('```');
      sections.push('');
    }
  }

  // Test results
  sections.push(`## Test Results\n`);
  if (testResult) {
    const statusIcon = testResult.passed ? 'PASS' : 'FAIL';
    sections.push(`**Status:** ${statusIcon}`);
    sections.push(`**Total:** ${testResult.total} | **Passed:** ${testResult.passed_count} | **Failed:** ${testResult.failed_count}`);
    sections.push('');

    // Self-correction iterations
    if (iterations && iterations.length > 1) {
      sections.push(`### Self-Correction Log\n`);
      sections.push(`The agent needed ${iterations.length - 1} correction(s) to fix test failures:\n`);
      for (const iter of iterations) {
        const icon = iter.result.passed ? '[PASS]' : '[FAIL]';
        sections.push(`- **${iter.label}**: ${icon} (${iter.result.passed_count}/${iter.result.total} passed)`);
        if (iter.correction && iter.correction.applied) {
          for (const c of iter.correction.corrections) {
            sections.push(`  - Correction: ${c.description || c.file}`);
          }
        }
      }
      sections.push('');
    }
  } else {
    sections.push('Tests were not run.');
    sections.push('');
  }

  // Risks
  if (plan.risksAndAssumptions && plan.risksAndAssumptions.length > 0) {
    sections.push(`## Risks & Assumptions\n`);
    for (const risk of plan.risksAndAssumptions) {
      sections.push(`- ${risk}`);
    }
    sections.push('');
  }

  // Footer
  sections.push('---');
  sections.push('*Generated by AI Coding Agent*');

  return sections.join('\n');
}

function generateBranchName(issue) {
  const slug = issue.title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 40);

  return `fix/${issue.number ? issue.number + '-' : ''}${slug}`;
}

function generateLabels(issue, plan) {
  const labels = ['automated-fix'];

  if (issue.labels.includes('bug')) labels.push('bug');
  if (plan.rootCause.includes('null')) labels.push('null-safety');

  return labels;
}

/**
 * Format the PR as a displayable string (for terminal output).
 */
export function formatPRForDisplay(pr) {
  const lines = [];
  const divider = '='.repeat(70);
  const thinDivider = '-'.repeat(70);

  lines.push('');
  lines.push(divider);
  lines.push('  PULL REQUEST');
  lines.push(divider);
  lines.push('');
  lines.push(`  Title:  ${pr.title}`);
  lines.push(`  Branch: ${pr.branch}`);
  lines.push(`  Labels: ${pr.labels.join(', ')}`);
  lines.push('');
  lines.push(thinDivider);
  lines.push('');
  lines.push(pr.body);
  lines.push('');
  lines.push(divider);

  return lines.join('\n');
}
