/**
 * Compliance Report Generator
 *
 * Generates structured Markdown reports with per-regulation pass/fail,
 * evidence trails, risk assessment, and remediation recommendations.
 */

export class ComplianceReporter {
  /**
   * Generate a full compliance report in Markdown.
   */
  generate({ complianceResults, riskAssessment, auditMeta = {} }) {
    const lines = [];
    const now = new Date().toISOString();

    // Header
    lines.push('# Compliance Audit Report');
    lines.push('');
    lines.push(`**Generated:** ${now}`);
    if (auditMeta.auditor) lines.push(`**Auditor:** ${auditMeta.auditor}`);
    if (auditMeta.scope) lines.push(`**Scope:** ${auditMeta.scope}`);
    if (auditMeta.period) lines.push(`**Period:** ${auditMeta.period}`);
    lines.push('');

    // Executive Summary
    lines.push('## Executive Summary');
    lines.push('');
    lines.push(`- **Overall Risk Level:** ${riskAssessment.overallRisk.toUpperCase()}`);
    lines.push(`- **Total Failures:** ${riskAssessment.totalFailures}`);
    lines.push(`- **Critical Findings:** ${riskAssessment.criticalFindings.length}`);
    lines.push('');

    if (riskAssessment.criticalFindings.length > 0) {
      lines.push('### Critical Findings Requiring Immediate Action');
      lines.push('');
      for (const finding of riskAssessment.criticalFindings) {
        lines.push(`- **${finding.name}** (${finding.ruleId}): ${finding.remediation}`);
      }
      lines.push('');
    }

    // Per-Regulation Results
    lines.push('## Regulation Results');
    lines.push('');

    // Group results by regulation
    const byRegulation = new Map();
    for (const result of complianceResults) {
      if (!byRegulation.has(result.regulation)) {
        byRegulation.set(result.regulation, []);
      }
      byRegulation.get(result.regulation).push(result);
    }

    for (const [regulation, results] of byRegulation) {
      const passed = results.filter(r => r.pass).length;
      const total = results.length;
      const score = total > 0 ? Math.round((passed / total) * 100) : 100;
      const status = score === 100 ? 'PASS' : score >= 70 ? 'PARTIAL' : 'FAIL';

      lines.push(`### ${regulation} — ${status} (${score}%)`);
      lines.push('');
      lines.push(`| Rule | Category | Severity | Status | Issues |`);
      lines.push(`|------|----------|----------|--------|--------|`);

      for (const r of results) {
        const statusIcon = r.pass ? 'PASS' : 'FAIL';
        lines.push(`| ${r.name} | ${r.category} | ${r.severity} | ${statusIcon} | ${r.failing} |`);
      }
      lines.push('');

      // Failing rules detail
      const failing = results.filter(r => !r.pass);
      if (failing.length > 0) {
        lines.push(`#### Failures Detail`);
        lines.push('');
        for (const r of failing) {
          lines.push(`**${r.name}** (${r.ruleId})`);
          lines.push(`- Severity: ${r.severity}`);
          lines.push(`- Description: ${r.description}`);
          lines.push(`- Failing items: ${r.failing} of ${r.total}`);
          lines.push(`- Remediation: ${r.remediation}`);
          if (r.evidence.length > 0) {
            lines.push(`- Evidence: ${JSON.stringify(r.evidence.slice(0, 3))}`);
          }
          lines.push('');
        }
      }
    }

    // Risk Matrix
    lines.push('## Risk Assessment');
    lines.push('');
    lines.push(`| Severity | Count |`);
    lines.push(`|----------|-------|`);
    for (const [sev, count] of Object.entries(riskAssessment.failedBySeverity)) {
      lines.push(`| ${sev} | ${count} |`);
    }
    lines.push('');

    // Remediation Roadmap
    const allFailing = complianceResults.filter(r => !r.pass);
    if (allFailing.length > 0) {
      lines.push('## Remediation Roadmap');
      lines.push('');

      const critical = allFailing.filter(r => r.severity === 'critical');
      const high = allFailing.filter(r => r.severity === 'high');
      const medium = allFailing.filter(r => r.severity === 'medium');

      if (critical.length > 0) {
        lines.push('### P0 — Critical (Immediate)');
        for (const r of critical) {
          lines.push(`- [ ] ${r.name}: ${r.remediation}`);
        }
        lines.push('');
      }
      if (high.length > 0) {
        lines.push('### P1 — High (Within 7 days)');
        for (const r of high) {
          lines.push(`- [ ] ${r.name}: ${r.remediation}`);
        }
        lines.push('');
      }
      if (medium.length > 0) {
        lines.push('### P2 — Medium (Within 30 days)');
        for (const r of medium) {
          lines.push(`- [ ] ${r.name}: ${r.remediation}`);
        }
        lines.push('');
      }
    }

    lines.push('---');
    lines.push('*Report generated by Compliance Audit Harness v1.0*');

    return lines.join('\n');
  }

  /**
   * Generate a summary-only report (no evidence detail).
   */
  generateSummary(complianceResults) {
    const lines = [];
    lines.push('# Compliance Summary');
    lines.push('');
    lines.push(`**Generated:** ${new Date().toISOString()}`);
    lines.push('');

    const byReg = new Map();
    for (const r of complianceResults) {
      if (!byReg.has(r.regulation)) byReg.set(r.regulation, { pass: 0, fail: 0 });
      const bucket = byReg.get(r.regulation);
      if (r.pass) bucket.pass++;
      else bucket.fail++;
    }

    lines.push('| Regulation | Passed | Failed | Score |');
    lines.push('|------------|--------|--------|-------|');
    for (const [reg, counts] of byReg) {
      const total = counts.pass + counts.fail;
      const score = total > 0 ? Math.round((counts.pass / total) * 100) : 100;
      lines.push(`| ${reg} | ${counts.pass} | ${counts.fail} | ${score}% |`);
    }

    return lines.join('\n');
  }
}
